GiftsExchange/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('events/',include('events.urls'))

    
]

accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('sign_in/', views.sign_in_view, name='sign_in_view'),
    path('sign_up/', views.sign_up_view, name='sign_up_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('profile/<username>', views.user_profile_view, name='user_profile_view'),

]

events/urls.py
from django.urls import path
from . import views

app_name='events'

urlpatterns=[
    path('create/',views.create_event_view,name='create_event_view')

]

main/urls.py
from django.urls import path 
from . import views 


app_name='main'


urlpatterns=[
    path("", views.home_view, name='home_view')
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    class GenderChoices(models.TextChoices):
        F= 'Female' , 'F'
        M= 'Male', 'M'
        NS='Not Specified','NS'
    user=models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True ,unique=True)
    gender=models.CharField(choices=GenderChoices.choices ,max_length=128 ,default=GenderChoices.NS)
    birth_date=models.DateField(blank=True ,null=True)  


    

events/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest , HttpResponse
from django.contrib.auth.models import User 
from django.contrib.auth import authenticate,login ,logout
from django.contrib import messages
from django.db import IntegrityError,transaction
from .models import Profile
# Create your views here.

def sign_up_view(request:HttpRequest):
    if request.method =='POST':
        try:
            with transaction.atomic():
                new_user=User.objects.create_user(username=request.POST['username'],password=request.POST['password'], email=request.POST['email'], first_name=request.POST['first_name'], last_name=request.POST['last_name'])
                new_user.save()
                profile:Profile=Profile(user=new_user)
                profile.save()

            messages.success(request, "Registered User Successfuly","alert-success")
            return redirect('accounts:sign_in_view')
        
        except IntegrityError as e :
            messages.error(request, "Please try another username. This username already in use","alert-danger")
            print("error :",e)
        except Exception as e:
            messages.error(request, "Could not register the user. Please again later","alert-danger")
            print("error :",e)
    return render(request, 'accounts/signup.html')

def sign_in_view(request:HttpRequest):
    if request.method =='POST':
        try:
            #check user cradentials
            user=authenticate(request,username=request.POST['username'],password= request.POST['password'])
            if user :
                #login the user
                login(request,user)
                messages.success(request, "Logged in Successfuly","alert-success")
                return redirect('main:home_view')
            else:
                messages.error(request, "Please try again. Your credentials are wrong.","alert-danger")
        except Exception as e:
            print("error :",e)
            messages.error(request, "Could not login. Try again","alert-danger")

    return render(request, 'accounts/signin.html')



def logout_view(request:HttpRequest):
    logout(request)
    messages.success(request, "Logged Out Successfuly","alert-success")

    return redirect('main:home_view')


def user_profile_view(request:HttpRequest, username):
    try:
        user= User.objects.get(username=username)
        if not Profile.objects.filter(user=user).first():
            new_profile = Profile(user=user)
            new_profile.save()


    except Exception as e:
        print(e)
    return render(request,"accounts/profile.html")

events/views.py
from django.shortcuts import render
from django.http import HttpRequest ,HttpResponse
# Create your views here.

def create_event_view(request:HttpRequest):
    return render(request, 'create_event.html')

main/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
# Create your views here.




def home_view(request:HttpRequest):
    return render(request, 'main/base.html')

accounts/templates/accounts/profile.html
{%extends 'main/base.html'%}

{%block content %}

<section class="row d-flex justify-content-center gap-3 mt-4">
    <div class="d-flex flex-row justify-content-between align-items-center px-4">
        <h3>My Account</h3>
        <a class="btn btn-danger" href="{%url 'accounts:logout_view'%}"><i class="bi bi-box-arrow-right"></i> Logout</a>

    </div>

    <hr>
    <section class="col-11 col-md-8 ">
        <h3>Personal information</h3>
        <div class="row d-flex flex-row justify-content-center justify-content-sm-start align-items-center card shadow">
            <div class='col-auto mx-auto mx-sm-1'>
                <i class="user-icon bi bi-person-circle"></i>
            </div>
            <div class='col-auto d-flex flex-column justify-content-start align-items-start py-sm-4'>

                <h5>@{{request.user.username}}</h5>
                <h6><span>Full Name : </span>{{request.user.get_full_name}}</h6>
                <h6><span>Email Adress : </span> {{request.user.email}}</h6>
                <h6><span>Gender : </span> {{request.user.profile.gender}}</h6>
                <h6><span>Date of birth : </span> {{request.user.profile.birth_date}}</h6>

            </div>
        </div>

    </section>
    <section class="col-11 col-md-8 ">
        <h3>Manage Account Settings</h3>
        <div class="row d-flex flex-row justify-content-center justify-content-sm-start align-items-center card shadow">
            <div class='col-auto m-3'>
                <a class="text-decoration-none w-100 ms-3 d-inline-flex justify-content-start" href="#">Change email address</a>
                <a class="text-decoration-none w-100 ms-3 d-inline-flex justify-content-start" href="#">Change password</a>
                <a class="text-decoration-none w-100 ms-3 d-inline-flex justify-content-start" href="#">Delete account</a>
                </div>
   
        </div>

    </section>
 
</section>




{%endblock%}

accounts/templates/accounts/signin.html
{%extends 'main/base.html'%}

{%block content %}

    <section class="main-section row d-flex justify-content-center">
        <div class='col-10 col-md-6 card-custom d-flex flex-column justify-content-center align-items-center py-2'>
            <h3>Sign in</h3>
            <form class="d-flex flex-column row-gap-2 px-2 w-100 " action="{%url 'accounts:sign_in_view'%}" method="POST">
                {% csrf_token %}
                <div class="form-floating">
                    <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Username" required >
                    <label for="inputUsername">Username</label>
                </div>
                <div class="form-floating"> 
                    <input type="password" class="form-control"  id="inputPassword" name="password" placeholder="Password" required>
                    <label for="inputPassword">Password</label>
                </div>
                <button type="submit" class="btn btn-danger">Sign in</button>
            </form>
            <a class="w-100 ms-3 d-inline-flex justify-content-start" href="#">Forget Password</a>

        </div>
    </section>




{%endblock%}

accounts/templates/accounts/signup.html
{%extends 'main/base.html'%}

{%block content %}

    <section class="main-section row d-flex justify-content-center">
        <div class='col-10 col-md-6 card-custom d-flex flex-column justify-content-center align-items-center py-2'>
            <h3>Sign Up</h3>
            <form class="d-flex flex-column row-gap-2 px-2 w-100 " action="{%url 'accounts:sign_up_view'%}" method="POST">
                {%csrf_token%}
                <div class="form-floating">
                    <input type="text" name="username" class="form-control" minlength="4" id="username" placeholder="Username" required >
                    <label for="username">Username</label>
                </div>
                <div class="form-floating">
                    <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email address" aria-describedby="emailHelp"
                       required >
                    <label for="inputEmail">Email address</label>
                </div>
                <div class="form-floating"> 
                    <input type="password" class="form-control" minlength="7" id="inputPassword" name="password" placeholder="Password" required>
                    <label for="inputPassword">Password</label>
                </div>
                <div class="form-floating">                    
                    <input type="text" name="first_name" class="form-control" minlength="3" id="firstName" placeholder="First Name" required>
                    <label for="firstName">First Name</label>
                </div>
                <div class="form-floating">                    
                    <input type="text" name="last_name" class="form-control" minlength="3" id="lastName" placeholder="Last Name" required>
                    <label for="lastName">Last Name</label>
                </div>
                <button type="submit" class="btn btn-danger">Sign up</button>
            </form>
        </div>
    </section>




{%endblock%}

main/templates/main/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/5.3/assets/css/docs.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}Gift Exchange{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</head>

{%url 'main:home_view' as home_url %}

<body>
    <header class="container-fuild fixid-top px-5">
        <nav class="navbar navbar-expand-md ">
            <div class="container-fluid">
                <a class="navbar-brand" href={{home_url}}>Gifts Exchange</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#right-nav"
                    aria-controls="right-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="right-nav">
                    <ul class="navbar-nav align-items-center ms-auto mb-2 mb-md-0 gap-3">
                        <li class="nav-item">
                            <a class="nav-link {%if request.path == home_url%}active{%endif%}" aria-current="page"
                                href="{{home_url}}">Home</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="#">Start New Event</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="#">My Events</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="#">Participation</a>
                        </li>
                        {%if request.user.is_authenticated%}
                        <li class="nav-item ">
                            <div class="user-info rounded-circle">
                                <button type="button" class="btn" data-bs-toggle="dropdown" data-bs-display="static"
                                    aria-expanded="false">
                                    <i class="bi bi-person-fill"></i> </button>
                                <ul class="dropdown-menu dropdown-menu-end p-4">
                                    <li>{{request.user.get_full_name}}</li>
                                    <li><a class="dropdown-item"
                                            href="{%url 'accounts:user_profile_view' request.user.username%}"><i
                                                class="bi bi-person-circle"></i> Profile</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{%url 'accounts:logout_view'%}"><i
                                                class="bi bi-box-arrow-right"></i> Logout</a></li>
                                </ul>
                            </div>
                        </li>
                        {%else%}
                        <li class="nav-item ">
                            <a href="{%url 'accounts:sign_in_view'%}" class="btn btn-outline-danger"
                                aria-disabled="true"><i class="bi bi-person-fill"></i></button>
                                sign in</a>
                        </li>
                        <li class="nav-item ">
                            <a href="{%url 'accounts:sign_up_view'%}" class="btn btn-danger" aria-disabled="true"><i
                                    class="bi bi-person-fill"></i></button>
                                sign up</a>
                        </li>

                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <main class="px-5">

        {%if messages%}
        {%for msg in messages%}
        <div class="alert {{msg.tags}} alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endfor%}
        {%endif%}
        {%block content%}

        {%endblock%}

    </main>
    <footer class="py-1 my-4">
        <ul class="nav justify-content-center align-items-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About us</a></li>
            <li class="nav-item"><a class="navbar-brand" href="{% url 'main:home_view' %}">Gifts Exchange</a> </li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Contact us</a></li>
        </ul>
        <p class="text-center text-body-secondary">&copy; 2025 All right reserved</p>

    </footer>

</body>

</html>